### ISSUE TITLE
usb메모리 => usb 메모리

### ISSUE THREAD

**Issue by skyer9** [lovit/soyspacing#3]
`usb메모리` 를 `usb` `메모리` 로 분리하도록 하고 싶은데요.

학습 데이터를 어떻게 준비하면 될까요?

3단우산도 역시 띄어져야 하고요.

**Comment by lovit** [comment]
soyspacing 뿐 아니라 학습데이터를 기반으로 하는 띄어쓰기 교정기는 실제로 학습데이터에 `usb 메모리` 로 띄어진 경우가 있거나, `usb` 다음에 빈 칸, 혹은 `메모리` 앞에 빈 칸에 자주 존재해야 합니다. `3단우산` 역시 `3단 우산`으로 띄어진 데이터가 있어야 띄어쓰기 기반 알고리즘은 작동합니다.

그런데 해결해야 하는 문제가 띄어쓰기 교정인가요? 아니면 토크나이징인가요? 토크나이징이라면 학습데이터에 `usb` 와 `메모리`가 각각 다른 단어로 들어 있다면 띄어질 것으로 생각됩니다.

**Comment by skyer9** [comment]
타겟 데이타가 고객 검색어 + 클릭한 상품명이라...
usb메모리 를 띄어 놓고 접근할려 했는데...

이번 이슈는 닫으셔도 될듯 해요.

접근법이 잘못된 듯 하네요.
첨부터 띄어쓰기 문제로 접근할게 아닌가 보네요.
(usb 검색어 입력하고 usb메모리 클릭하는 사람이 많다는)

**Comment by skyer9** [comment]
드디어 만족스러운 결과를 얻었네요.
목표는 쇼핑몰 상품명 띄어쓰기 적용이었는데
`soyspacing` 만 이용해 결과를 얻게되었습니다.

감사합니다.
